name: clean_rl_mn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.2
  - pandas=2.3
  - scipy=1.15
  - matplotlib=3.10
  - seaborn=0.13
  - statsmodels=0.14
  - tensorboard=2.20
  - wandb=0.25
  - av=16.0
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.12.0+cu126
      - torchinfo==1.8.0
      - moviepy==2.2.1
      - einops==0.7.0
      - gymnasium==0.29.0
      - memory-gym==1.0.2
      - minigrid==2.5.0
      - opencv-python==4.11.0.86
      - reprint==0.6.0
      - tyro==0.8.14
