anneal_steps: 4096000
apply_memory_masks: false
clip_coef: 0.2
clip_vloss: true
cuda: true
env_id: MiniGrid-MemoryS9-v0
exp_name: run_for_m_testing_normal
final_ent_coef: 1.0e-06
final_lr: 1.0e-05
gae_lambda: 0.95
gamma: 0.995
hindsight_at_0: false
init_ent_coef: 0.0001
init_lr: 0.000275
max_grad_norm: 0.25
norm_adv: false
num_envs: 16
num_minibatches: 8
num_rollout_steps: 256
reconstruction_coef: 0.0
seed: 1
target_kl: null
torch_deterministic: true
total_timesteps: 2048000
trxl_dim: 256
trxl_memory_length: 64
trxl_num_heads: 4
trxl_num_layers: 2
trxl_positional_encoding: absolute
uniform_attention_on_fully_masked_rows: true
update_epochs: 3
use_old_bootstrap: true
use_spatial_memory: false
vf_coef: 0.5
