import numpy as np
from PIL import Image, ImageDraw, ImageFont


class AgentViewRenderer:
    """
    This class was entirely generated by AI.

    Renders frames for the agent's view of the gridworld, showing:
        - The agent's current perceived position (red dot)
        - The history of perceived positions (visited cells filled light grey)
        - Past memory retrieval positions (yellow borders)
        - Next memory retrieval position (orange border + semi-transparent fill)
        - A legend explaining the symbols
        - A memory timeline on the right showing which env steps have been visited and/or retrieved
    """

    # ── single source of truth for colours (spatial grid & temporal timeline) ──
    COLOR_BG = (30, 30, 40)
    COLOR_GRID_LINE = (60, 60, 75)
    COLOR_ORIGIN = (80, 130, 255)  # blue – grid origin / t=0
    COLOR_AGENT = (220, 50, 50)  # red – agent position / current step
    COLOR_VISITED = (75, 75, 90)  # grey – visited cells / visited steps
    COLOR_CUMULATIVE_FOV = (50, 140, 140)  # dim teal – all cells ever observed
    COLOR_PAST_RETRIEVAL = (180, 165, 50)  # muted gold – past retrieval positions
    COLOR_CURRENT_RETRIEVED = (255, 50, 200)  # hot pink – steps currently in memory window
    COLOR_NEXT_RETRIEVAL = (255, 140, 0)  # orange – next retrieval position

    def __init__(
        self,
        grid_w,
        grid_h,
        max_episode_steps: int,
        res: int = 16,
    ):
        self.grid_w = grid_w
        self.grid_h = grid_h
        self.max_episode_steps = max_episode_steps
        self.agent_perceived_pos_history = []
        self.past_memory_retrieval_positions = []
        self.res = res

        # memory timeline state (updated each frame)
        self._current_env_t: int | None = None
        self._retrieved_steps: set[int] = set()  # env steps currently being retrieved
        self._ever_retrieved_steps: set[int] = set()  # env steps ever retrieved (cumulative)
        self._visited_steps: set[int] = set()  # env steps visited so far
        self._retrieved_fov: np.ndarray | None = (
            None  # (W, H) bool — cells in current memory window
        )
        self._cumulative_fov: np.ndarray | None = None  # (W, H) bool — all cells ever observed
        self._lower_bound_min_steps: int | None = None

        # ── rendering caches (built once, survive reset) ────────────────────────
        self._grid_bg: Image.Image | None = None  # blank RGBA: grid lines + origin dot
        self._tl_bare: Image.Image | None = None  # bare timeline: all future squares + labels

    def reset(self):
        self.agent_perceived_pos_history = []
        self.past_memory_retrieval_positions = []
        self._current_env_t = None
        self._retrieved_steps = set()
        self._ever_retrieved_steps = set()
        self._visited_steps = set()
        self._retrieved_fov = None
        self._cumulative_fov = None
        self._lower_bound_min_steps = None

    def add_frame_info(
        self,
        agent_pos,
        memory_retrieval_pos,
        current_env_t: int | None = None,
        memory_indices_env: np.ndarray | None = None,
        memory_masks: np.ndarray | None = None,
        retrieved_fov: np.ndarray | None = None,
        cumulative_fov: np.ndarray | None = None,
        lower_bound_min_steps: int | None = None,
    ):
        if agent_pos is not None:
            self.agent_perceived_pos_history.append(agent_pos)
        if memory_retrieval_pos is not None:
            self.past_memory_retrieval_positions.append(memory_retrieval_pos)

        if current_env_t is not None:
            self._current_env_t = current_env_t
            self._visited_steps.add(current_env_t)

        if memory_indices_env is not None and memory_masks is not None:
            self._retrieved_steps = set()
            for idx, mask in zip(memory_indices_env, memory_masks):
                if mask:
                    self._retrieved_steps.add(int(idx))
            self._ever_retrieved_steps |= self._retrieved_steps

        if lower_bound_min_steps is not None:
            self._lower_bound_min_steps = lower_bound_min_steps

        self._retrieved_fov = retrieved_fov
        self._cumulative_fov = cumulative_fov

    def generate_frame(self):

        last_agent_pos = (
            self.agent_perceived_pos_history[-1] if self.agent_perceived_pos_history else None
        )
        current_memory_retrieval_position = (
            self.past_memory_retrieval_positions[-1]
            if self.past_memory_retrieval_positions
            else None
        )
        cell_size = self.res  # pixels per cell
        num_cols = 2 * self.grid_w  # from -grid_w+1 to +grid_w-1
        num_rows = 2 * self.grid_h  # from -grid_h+1 to +grid_h-1
        img_w = cell_size * num_cols
        img_h = cell_size * num_rows

        # ── colours (from class-level single source of truth) ───────────────────────
        BG = self.COLOR_BG
        VISITED_CELL = self.COLOR_VISITED
        AGENT = self.COLOR_AGENT
        MEM_PAST_BORDER = self.COLOR_PAST_RETRIEVAL
        MEM_NEXT_BORDER = self.COLOR_NEXT_RETRIEVAL
        MEM_NEXT_FILL = (*self.COLOR_NEXT_RETRIEVAL, 160)

        # Use RGBA so we can paint the semi-transparent current-retrieval fill
        if self._grid_bg is None:
            self._grid_bg = self._build_grid_bg()
        img = self._grid_bg.copy()
        draw = ImageDraw.Draw(img)

        def cell_rect(gx, gy):
            px = (gx + self.grid_w) * cell_size
            py = (gy + self.grid_h) * cell_size
            x0 = px + 1
            y0 = py + 1
            x1 = px + cell_size - 2
            y1 = py + cell_size - 2
            return [x0, y0, x1, y1]

        def cell_center(gx, gy):
            px = (gx + self.grid_w) * cell_size
            py = (gy + self.grid_h) * cell_size
            return (px + cell_size // 2, py + cell_size // 2)

        # ── visited cell fills – drawn first so FOV overlays tint on top ──────
        visited = set(map(tuple, self.agent_perceived_pos_history))
        for pos in visited:
            draw.rectangle(cell_rect(*pos), fill=(*VISITED_CELL, 255))

        # ── cumulative FOV + retrieved FOV – draw both on a single overlay ─────
        need_overlay = (self._cumulative_fov is not None) or (self._retrieved_fov is not None)
        if need_overlay:
            fov_overlay = Image.new("RGBA", (img_w, img_h), (0, 0, 0, 0))
            fov_draw = ImageDraw.Draw(fov_overlay)
            if self._cumulative_fov is not None:
                cox, coy = self.grid_w - 1, self.grid_h - 1
                for i, j in zip(*np.where(self._cumulative_fov)):
                    gx, gy = int(i) - cox, int(j) - coy
                    fov_draw.rectangle(cell_rect(gx, gy), fill=(*self.COLOR_CUMULATIVE_FOV, 40))
            if self._retrieved_fov is not None:
                ox, oy = self.grid_w - 1, self.grid_h - 1
                for i, j in zip(*np.where(self._retrieved_fov)):
                    gx, gy = int(i) - ox, int(j) - oy
                    fov_draw.rectangle(cell_rect(gx, gy), fill=(*self.COLOR_CURRENT_RETRIEVED, 100))
            img = Image.alpha_composite(img, fov_overlay)
            draw = ImageDraw.Draw(img)

        def draw_square(cx, cy, half_size, outline=None, outline_width=2):
            bbox = [cx - half_size, cy - half_size, cx + half_size, cy + half_size]
            draw.rectangle(bbox, outline=outline, width=outline_width)

        def draw_circle(cx, cy, radius, fill=None, outline=None, outline_width=2):
            bbox = [cx - radius, cy - radius, cx + radius, cy + radius]
            draw.ellipse(bbox, fill=fill, outline=outline, width=outline_width)

        border_r = max(3, cell_size // 2 - 2)  # border circles hug the cell
        border_w = max(2, cell_size // 8)
        agent_r = max(3, cell_size // 3)

        # ── past memory retrieval positions – yellow border only ───────────────
        for pos in self.past_memory_retrieval_positions:
            cx, cy = cell_center(*pos)
            draw_square(cx, cy, border_r, outline=(*MEM_PAST_BORDER, 255), outline_width=border_w)

        # ── next memory retrieval – orange border + semi-transparent fill ───
        if current_memory_retrieval_position is not None:
            cx, cy = cell_center(*current_memory_retrieval_position)
            # Semi-transparent fill on a separate layer so it composites cleanly
            overlay = Image.new("RGBA", (img_w, img_h), (0, 0, 0, 0))
            ov_draw = ImageDraw.Draw(overlay)
            ov_draw.ellipse(
                [cx - border_r, cy - border_r, cx + border_r, cy + border_r],
                fill=MEM_NEXT_FILL,
            )
            img = Image.alpha_composite(img, overlay)
            draw = ImageDraw.Draw(img)  # rebind after composite
            draw_square(cx, cy, border_r, outline=(*MEM_NEXT_BORDER, 255), outline_width=border_w)

        # ── agent – red dot ────────────────────────────────────────────────────
        if last_agent_pos is not None:
            cx, cy = cell_center(*last_agent_pos)
            draw_circle(cx, cy, agent_r, fill=(*AGENT, 255))

        # ── legend ─────────────────────────────────────────────────────────────
        legend_w = max(160, cell_size * 8)  # wider to accommodate bar + squares + labels
        swatch = max(8, cell_size // 2)
        pad = max(4, cell_size // 4)
        font_size = max(10, swatch)
        font = ImageFont.load_default()

        legend_items = [
            (AGENT, "circle", "Agent"),
            (VISITED_CELL, "rect", "Visited"),
            (self.COLOR_CUMULATIVE_FOV, "rect", "Seen (FOV)"),
            (self.COLOR_ORIGIN, "circle", "Origin / t=0"),
            (MEM_PAST_BORDER, "square_border", "Past retrieval"),
            (self.COLOR_CURRENT_RETRIEVED, "rect", "Cur. retrieved"),
            (MEM_NEXT_BORDER, "square_border", "Next retrieval"),
        ]

        canvas = Image.new("RGBA", (img_w + legend_w, img_h), (*BG, 255))
        canvas.paste(img, (0, 0))
        ld = ImageDraw.Draw(canvas)

        y_off = pad
        for color, style, label in legend_items:
            sx = img_w + pad
            sy = y_off
            if style == "circle":
                ld.ellipse([sx, sy, sx + swatch, sy + swatch], fill=(*color, 255))
            elif style == "rect":
                ld.rectangle([sx, sy, sx + swatch, sy + swatch], fill=(*color, 255))
            elif style == "square_border":
                bw = max(1, swatch // 6)
                ld.rectangle([sx, sy, sx + swatch, sy + swatch], outline=(*color, 255), width=bw)
            tx = sx + swatch + pad
            ty = sy + (swatch - font_size) // 2
            ld.text((tx, ty), label, fill=(200, 200, 200, 255), font=font)
            y_off += swatch + pad

        # ── flatten to RGB and return as numpy array ───────────────────────────
        # Draw the memory timeline vertically on the right side, below the legend
        canvas = self._draw_memory_timeline(canvas, font, x_start=img_w + pad, y_start=y_off)
        return np.array(canvas.convert("RGB"))

    def _build_grid_bg(self) -> Image.Image:
        """Build a cached blank RGBA image with grid lines and origin dot drawn."""
        cell_size = self.res
        num_cols = 2 * self.grid_w
        num_rows = 2 * self.grid_h
        img_w = cell_size * num_cols
        img_h = cell_size * num_rows
        BG = self.COLOR_BG
        GRID_LINE = self.COLOR_GRID_LINE
        img = Image.new("RGBA", (img_w, img_h), (*BG, 255))
        draw = ImageDraw.Draw(img)
        for col in range(num_cols + 1):
            x = col * cell_size
            draw.line([(x, 0), (x, img_h)], fill=(*GRID_LINE, 255), width=1)
        for row in range(num_rows + 1):
            y = row * cell_size
            draw.line([(0, y), (img_w, y)], fill=(*GRID_LINE, 255), width=1)
        # origin dot at grid centre (0, 0)
        cx = self.grid_w * cell_size + cell_size // 2
        cy = self.grid_h * cell_size + cell_size // 2
        r = max(2, cell_size // 6)
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(*self.COLOR_ORIGIN, 255))
        return img

    def _build_timeline_bare(
        self,
        canvas_size: tuple[int, int],
        x_sq: int,
        x_bar: int,
        bar_w: int,
        y_top: int,
        sq: int,
        pad: int,
        label_step: int,
        font,
        num_font_size: int,
        M: int,
    ) -> Image.Image:
        """Pre-render all M timeline squares in 'future' style on a transparent layer.

        Composited onto the canvas once per frame; only the dynamic cells
        (t <= current_env_t) are then drawn on top, saving M-current_env_t
        draw.rectangle calls per frame.
        """
        BG_DARK = (*self.COLOR_BG, 255)
        TEXT = (200, 200, 200, 255)
        bare = Image.new("RGBA", canvas_size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(bare)
        for t in range(M):
            y = y_top + t * sq
            draw.rectangle(
                [x_sq, y, x_sq + sq, y + sq],
                fill=BG_DARK,
                outline=(42, 42, 54, 255),
                width=1,
            )
            if t % label_step == 0 or t == M - 1:
                draw.text(
                    (x_sq + sq + pad, y + (sq - num_font_size) // 2),
                    str(t),
                    fill=TEXT,
                    font=font,
                )
        return bare

    def _draw_memory_timeline(
        self, canvas: Image.Image, font, x_start: int, y_start: int
    ) -> Image.Image:
        """Draw a vertical Zahlenstrahl of touching squares on the right panel.

        Full dualism with the spatial grid view — every legend item maps to
        the same colour in both views:

        - Grey fill      → visited step             (= grey visited cell)
        - Teal tint      → seen (FOV)               (= teal cumulative FOV overlay)
        - Gold border    → past retrieval            (= gold border on past retrieval positions)
        - Pink fill+bar  → currently retrieved       (= pink overlay on retrieved FOV cells)
        - Orange border  → next retrieval / current  (= orange border on retrieval head)
        - Red arrow      → agent / current step      (= red dot at agent position)
        - Blue outline   → t=0 (temporal origin)     (= blue dot at grid origin)
        """
        if self._current_env_t is None:
            return canvas

        M = self.max_episode_steps
        pad = max(2, self.res // 8)
        title_h = max(10, self.res // 2)

        # Available height for the strip (no padding between squares)
        avail_h = canvas.size[1] - y_start - title_h - pad
        sq = max(1, avail_h // M)  # shrink down to 1px per step if needed

        bar_w = max(4, sq * 2)  # wide retrieval bar to the left of the squares
        arrow_w = max(6, sq) + pad  # space for the arrow, left of the bar

        # x of the bar and squares (bar sits between arrow and squares)
        x_bar = x_start + arrow_w
        x_sq = x_bar + bar_w + pad
        y_top = y_start + title_h + pad

        # Show at most 10 labels (plus always the last step)
        label_step = max(1, M // 10)
        num_font_size = max(7, min(sq, 12))

        # ── build bare timeline once, composite onto canvas ────────────────────
        if self._tl_bare is None:
            self._tl_bare = self._build_timeline_bare(
                canvas.size, x_sq, x_bar, bar_w, y_top, sq, pad, label_step, font, num_font_size, M
            )
        canvas = Image.alpha_composite(canvas, self._tl_bare)
        draw = ImageDraw.Draw(canvas)

        # Colours – all derived from class constants (single source of truth)
        VISITED = (*self.COLOR_VISITED, 255)
        FOV_TINT = (*self.COLOR_CUMULATIVE_FOV, 80)  # semi-transparent teal layer
        PAST_RETR = (*self.COLOR_PAST_RETRIEVAL, 255)
        CUR_RETR = (*self.COLOR_CURRENT_RETRIEVED, 255)
        NEXT_RETR = (*self.COLOR_NEXT_RETRIEVAL, 255)
        AGENT_RED = (*self.COLOR_AGENT, 255)
        ORIGIN_BLUE = (*self.COLOR_ORIGIN, 255)
        GRID_LINE = (*self.COLOR_GRID_LINE, 255)
        TEXT = (200, 200, 200, 255)
        BG_DARK = (*self.COLOR_BG, 255)
        LB_COLOR = (100, 200, 255, 255)  # light blue – lower bound min steps

        # ── title ──────────────────────────────────────────────────────────
        draw.text((x_start, y_start), "Timeline:", fill=TEXT, font=font)

        # ── teal FOV overlay on a separate RGBA layer (like spatial FOV) ───────
        fov_layer = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
        fov_draw = ImageDraw.Draw(fov_layer)

        # ── draw only past/present steps (future steps already in _tl_bare) ──
        for t in range(self._current_env_t + 1):
            y = y_top + t * sq

            # ── retrieval bar – wide filled strip to the left of the square ──
            if t in self._retrieved_steps:
                draw.rectangle(
                    [x_bar, y, x_bar + bar_w, y + sq],
                    fill=CUR_RETR,
                )

            # ── square fill: layer grey visited, then pink if retrieved ────────
            fill_color = BG_DARK
            if t in self._visited_steps:
                fill_color = VISITED  # grey, like visited cells on the grid

            if t in self._retrieved_steps:
                fill_color = CUR_RETR  # pink on top, like retrieved FOV overlay

            # ── square outline: determine border ───────────────────────────────
            outline_color = GRID_LINE
            outline_w = 1

            if t == 0:
                # t=0 ↔ spatial origin (blue)
                outline_color = ORIGIN_BLUE
                outline_w = max(1, sq // 4)

            if t in self._ever_retrieved_steps and t not in self._retrieved_steps:
                # past retrieval (gold border), like gold border on past retrieval positions
                outline_color = PAST_RETR
                outline_w = max(1, sq // 4)

            if t == self._current_env_t:
                # current step ↔ next retrieval / agent (orange border)
                outline_color = NEXT_RETR
                outline_w = max(1, sq // 4)

            draw.rectangle(
                [x_sq, y, x_sq + sq, y + sq],
                fill=fill_color,
                outline=outline_color,
                width=outline_w,
            )

            # ── teal FOV tint on visited steps (layered on top, like spatial) ─
            if t in self._visited_steps:
                fov_draw.rectangle(
                    [x_sq, y, x_sq + sq, y + sq],
                    fill=FOV_TINT,
                )

            # ── red right-pointing arrow for current env_t (= agent marker) ──
            if t == self._current_env_t:
                cx = x_start + arrow_w // 2
                cy = y + sq // 2
                tri = max(2, sq // 3)
                draw.polygon(
                    [(cx - tri, cy - tri), (cx - tri, cy + tri), (cx + tri, cy)],
                    fill=AGENT_RED,
                )

        # composite teal FOV layer on top
        canvas = Image.alpha_composite(canvas, fov_layer)
        draw = ImageDraw.Draw(canvas)

        # ── lower bound min steps – horizontal line to the left of the squares ──
        if self._lower_bound_min_steps is not None and 0 <= self._lower_bound_min_steps < M:
            lb_y = y_top + self._lower_bound_min_steps * sq
            line_x0 = x_bar
            line_x1 = x_sq + sq
            line_w = max(1, sq // 4)
            draw.line([(line_x0, lb_y), (line_x1, lb_y)], fill=LB_COLOR, width=line_w)
            # label to the right, offset past the step numbers
            label_x = x_sq + sq + pad + num_font_size * 2 + pad
            draw.text(
                (label_x, lb_y - num_font_size // 2),
                f"lb={self._lower_bound_min_steps}",
                fill=LB_COLOR,
                font=font,
            )

        return canvas


if __name__ == "__main__":
    # Example usage

    av_renderer = AgentViewRenderer(
        grid_w=8,
        grid_h=8,
        max_episode_steps=10,
        res=32,
    )
    av_renderer.add_frame_info(
        agent_pos=(-3, -2),
        memory_retrieval_pos=(2, 2),
        current_env_t=0,
        memory_indices_env=np.array([0]),
        memory_masks=np.array([True]),
    )
    av_renderer.add_frame_info(
        agent_pos=(-3, -1),
        memory_retrieval_pos=(2, 2),
        current_env_t=1,
        memory_indices_env=np.array([0, 1]),
        memory_masks=np.array([True, True]),
    )
    av_renderer.add_frame_info(
        agent_pos=(-3, 0),
        memory_retrieval_pos=(-3, 0),
        current_env_t=2,
        memory_indices_env=np.array([0, 1, 2]),
        memory_masks=np.array([True, True, True]),
    )
    av_renderer.add_frame_info(
        agent_pos=(-4, 0),
        memory_retrieval_pos=(1, 1),
        current_env_t=3,
        memory_indices_env=np.array([1, 3]),
        memory_masks=np.array([True, True]),
    )
    av_renderer.add_frame_info(
        agent_pos=(-5, 0),
        memory_retrieval_pos=(1, 1),
        current_env_t=4,
        memory_indices_env=np.array([0, 2, 3]),
        memory_masks=np.array([True, True, True]),
    )

    frame = av_renderer.generate_frame()  # get the current frame as a numpy array
    print(frame.shape)  # (256, 256, 3)

    # Quick preview
    Image.fromarray(frame).show()
