anneal_steps: 4096000
apply_memory_masks: false
checkpoint_path: trained_models/cherry_models/MiniGrid-MemoryS9-v0__run_for_m_testing_normal__1__04-08_23:38/checkpoints/i_115200__r_0.964/model_params
checkpoint_submodules:
- encoder
- transformer
- hidden_post_trxl
- actor_branches
- critic
clip_coef: 0.2
clip_vloss: true
cuda: true
env_id: MiniGrid-MemoryS9-v0
exp_name: add_grid_cell
final_ent_coef: 1.0e-06
final_lr: 1.0e-06
gae_lambda: 0.95
gamma: 0.995
grid_cell_encoding: true
grid_cell_encoding_weight: 0.5
hindsight_at_0: false
init_ent_coef: 0.0001
init_lr: 2.75e-05
internal_ent_coef: 0.01
internal_head_warmup_steps: -1
max_grad_norm: 0.25
norm_adv: false
num_envs: 16
num_minibatches: 8
num_rollout_steps: 256
prior_pe: false
reconstruction_coef: 0
retrieval_reward_coef: 0
seed: 1
spatial_head_type: categorical_xy
target_kl: null
torch_deterministic: true
total_timesteps: 2048000
trxl_dim: 256
trxl_memory_length: 64
trxl_num_heads: 4
trxl_num_layers: 2
trxl_positional_encoding: absolute
uniform_attention_on_fully_masked_rows: true
update_epochs: 3
use_old_bootstrap: true
use_spatial_memory: false
vf_coef: 0.5
